### ISSUE TITLE
Problem in Phase2 run

### ISSUE THREAD

**Issue by jerry1gotobed** [kt-korbeld/pyFRESCO#1]
Dear Developer,

When I run the code:
python DistributeFoldx.py Phase2 5XH3_protein.pdb 10
There is some error.

'''
This is a python implementation of the DistributeFoldx script written by Hein Wijma.
The script requires less inputs than the original script. by setting LEGACY to True inside the script,
it wil instead use the original input structure. Legacy mode is currently OFF.
This program is intended to distribute the calculation of a large number of mutations by FoldX.
For the first phase of preparing the files for calculations, use a command like:

        python DistributeFoldX.py Phase1 MyPrecious.pdb MyPreciousSelection.tab 100 /home/wijma/Fold_X/FoldX.linux64 

This should PREPARE mutations of MyPrecious.pdb for residues specified in the File MyPreciousSelection.tab and
distribute them over directories with each a 100 different mutations. For the second phase of collecting the results into a list, use a command like:

        python DistributeFoldX.py Phase2 MyPrecious.pdb -5 

This should COLLECT the mutations of MyPrecious.pdb assuming a cutoff of -5 KJ mol-1,resulting in FOUR lists:
- a complete list of all mutations
- a list of the mutations that are less than -5 kJ mol-1
- a list with the best mutation per position
- a list with the best mutation per position that are less than -5 kJ mol-1

Now performing:  Phase2
Mutation energy Cutoff:  10.0
Found 1 Subdirectories

Currently looking for Subdirectory1/Average_5XH3_protein.fxout....
Subdirectory1/Average_5XH3_protein.fxout does not exist, cant read energies
‘’‘’

Is it because
- The foldx version?
- The pdb should be clean?

**Comment by jerry1gotobed** [comment]
I tried Foldx5.1, buy still meet the error

**Comment by jerry1gotobed** [comment]
python 3.9.19
numpy 2.0.1
5XH3_protein.pdb: only ATOM line(I also tried the 5XH3.pdb,still have the problem)

5XH3.tab:

N A 1
P A 2
Y A 3
END

**Comment by jerry1gotobed** [comment]
python 3.9.19
numpy 2.0.1
5XH3_protein.pdb: only ATOM line(I also tried the 5XH3.pdb,still have the problem)

5XH3.tab:

1 A N
2 A P
3 A Y
END

**Comment by jerry1gotobed** [comment]
python 3.9.19
numpy 2.0.1
5XH3_protein.pdb: only ATOM line(I also tried the 5XH3.pdb,still have the problem)

5XH3.tab:

N A 1
P A 2
Y A 3
END

**Comment by kt-korbeld** [comment]
Hey Jerry,

Glad to see you interested in using the scripts! Are you sure the FoldX
calculations themselves have been run? (i.e did the todolist script
successfully finish and does a .fxout file exist in Subdirectory1?) The
script only prepares all the folders (in Phase1) and collects the FoldX
output (in Phase2) in between the user has to run the FoldX calculations
using the todolist script generated in Phase1 themselves. This was done so
that the actual FoldX calculations can be submitted to a high performance
cluster if needed. A more detailed step-by-step write up of how the
original scripts are used can be found here:
https://link.springer.com/protocol/10.1007/978-1-4939-7366-8_5

 If the .fxout file does in fact exist and the error persists, please email
me the .fxout file and i'll try to replicate the error (this might take a
bit longer, i am on holidays for a week)

Cheers,
Kerlen

**Comment by jerry1gotobed** [comment]
Oh
So after I run    
**python DistributeFoldX.py Phase1 MyPrecious.pdb MyPreciousSelection.tab 100 /home/wijma/Fold_X/FoldX.linux64 .**

Next I should run
**./todolist**

Then 
 **python DistributeFoldX.py Phase2 MyPrecious.pdb -5** 

right?

**Comment by jerry1gotobed** [comment]
And  I have another question. I did not find 'fix_bb_monomer_ddg.linuxgccrelease' in Rosetta bin directory.
Is the "fix_bb_monomer_ddg.linuxgccrelease" just the "ddg_monomer.linuxgccrelease"?

**Comment by jerry1gotobed** [comment]
> Oh So after I run **python DistributeFoldX.py Phase1 MyPrecious.pdb MyPreciousSelection.tab 100 /home/wijma/Fold_X/FoldX.linux64 .**
> 
> Next I should run **./todolist**
> 
> Then **python DistributeFoldX.py Phase2 MyPrecious.pdb -5**
> 
> right?

Yeah, it is solved now.

**Comment by jerry1gotobed** [comment]
And I have another question. I did not find 'fix_bb_monomer_ddg.linuxgccrelease' in Rosetta bin directory.
Is the "fix_bb_monomer_ddg.linuxgccrelease" just the "ddg_monomer.linuxgccrelease"?

**Comment by jerry1gotobed** [comment]
When I run this command, there is Rosetta crash error.

python DistributeRosettaddg.py Phase1 MyPrecious.pdb MyPreciousSelection.tab 100 FLAGrow3 /root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/bin/ddg_monomer.mpi.linuxgccrelease

###############################################################################
# Rosetta crash log. Please submit the contents of this file to http://crash.rosettacommons.org/
# or use the script Rosetta/main/source/scripts/python/public/report_crashes.py
#

[START_CRASH_REPORT]
[ROSETTA_VERSION]: 2021.16+release.8ee4f02
[COMMIT_DATE]: 2021-04-20T20:57:38.289184
[APPLICATION]: /root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/bin/ddg_monomer.mpi.linuxgccrelease
[MODE]: Release
[EXTRAS]: mpi (OpenMPI 4.1.5) 
[OS]: GNU/Linux
[COMPILER]: GCC version "9.4.0"
[STDLIB]: libstdc++ version 20210601
[START_OPTIONS]
 -in:path:database=-database/ /Users/heinwijma/frescoSoftware/rosetta_bin_mac_2015.20.57849_bundle/main/database/ -in:file:s=5XH3_protein.pdb -ddg:min_cst=false -ddg:local_opt_only -ddg:mean -ddg:min=false -ddg:sc_min_only=false -ddg:opt_radius=8 -ddg:ramp_repulsive=false -ddg:mut_file=RosettaFormatMutations.mut -ddg:iterations=50 -ddg:dump_pdbs=false -ddg:weight_file=soft_rep_design

[END_OPTIONS]

[START_BACKTRACE]: RAW_LIBC
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libutility.so(backtrace_string[abi:cxx11](int)+0x43) [0x7f5f3c5b4b53]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libutility.so(utility::excn::Exception::Exception(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xe3) [0x7f5f3c5eba03]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libutility.so(utility::UtilityExitException::UtilityExitException(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xfb) [0x7f5f3c5b8fbb]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libutility.so(utility::exit(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x37) [0x7f5f3c5b8c27]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.2.so(core::chemical::GlobalResidueTypeSet::init_restypes_from_database()+0x93e) [0x7f5f3d89b41e]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.2.so(core::chemical::GlobalResidueTypeSet::GlobalResidueTypeSet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1e4) [0x7f5f3d8ab234]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.2.so(core::chemical::ChemicalManager::create_residue_type_set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x1de) [0x7f5f3d87524e]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.2.so(std::_Function_handler<std::shared_ptr<core::chemical::GlobalResidueTypeSet> (), std::_Bind<std::shared_ptr<core::chemical::GlobalResidueTypeSet> (core::chemical::ChemicalManager::*(core::chemical::ChemicalManager*, std::reference_wrapper<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const> >::_M_invoke(std::_Any_data const&)+0x28) [0x7f5f3d8775c8]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.2.so(core::chemical::ChemicalManager::residue_type_set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1a4) [0x7f5f3d874234]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.2.so(core::chemical::ChemicalManager::residue_type_set(core::chemical::TypeSetMode)+0x2a) [0x7f5f3d87487a]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.2.so(core::conformation::Conformation::residue_type_set_for_conf(core::chemical::TypeSetMode) const+0xdf) [0x7f5f3dbacdef]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.3.so(core::pose::Pose::residue_type_set_for_pose(core::chemical::TypeSetMode) const+0xe) [0x7f5f3eb1fd4e]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.6.so(core::import_pose::pose_from_file(core::pose::Pose&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, core::import_pose::ImportPoseOptions const&, bool, core::import_pose::FileType)+0xdc) [0x7f5f41eff88c]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/build/src/release/linux/6.1/64/x86/gcc/9.4/mpi/libcore.6.so(core::import_pose::pose_from_file(core::pose::Pose&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, core::import_pose::FileType)+0x39) [0x7f5f41effa69]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/bin/ddg_monomer.mpi.linuxgccrelease(+0xd42e) [0x557bdb58442e]
/lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7f5f3ae6324a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f5f3ae63305]
/root/rosetta/rosetta_src_2021.16.61629_bundle/main/source/bin/ddg_monomer.mpi.linuxgccrelease(+0x11a3d) [0x557bdb588a3d]

[END_BACKTRACE]
#########################################################################################


I did not find where to modify the database in the DistributeRosettaddg.py.

**Comment by kt-korbeld** [comment]
Heya, sorry for the late reply, the database is specified in the FLAGROW3
file and can be changed there. I apologize if some steps are a bit obscure
and not specified on the github, as they assume the user is following the
setup and steps in the FRESCO protocol.
Good luck!

Cheers,
Kerlen

**Comment by jerry1gotobed** [comment]
OK, it can run now. Thank you!
